/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package mx.com.cuervo.rutas.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the Parada service. Represents a row in the &quot;C_Parada&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>mx.com.cuervo.rutas.model.impl.ParadaModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>mx.com.cuervo.rutas.model.impl.ParadaImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Parada
 * @generated
 */
@ProviderType
public interface ParadaModel
	extends BaseModel<Parada>, GroupedModel, ShardedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a parada model instance should use the {@link Parada} interface instead.
	 */

	/**
	 * Returns the primary key of this parada.
	 *
	 * @return the primary key of this parada
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this parada.
	 *
	 * @param primaryKey the primary key of this parada
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the parada ID of this parada.
	 *
	 * @return the parada ID of this parada
	 */
	public long getParadaId();

	/**
	 * Sets the parada ID of this parada.
	 *
	 * @param paradaId the parada ID of this parada
	 */
	public void setParadaId(long paradaId);

	/**
	 * Returns the group ID of this parada.
	 *
	 * @return the group ID of this parada
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this parada.
	 *
	 * @param groupId the group ID of this parada
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this parada.
	 *
	 * @return the company ID of this parada
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this parada.
	 *
	 * @param companyId the company ID of this parada
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this parada.
	 *
	 * @return the user ID of this parada
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this parada.
	 *
	 * @param userId the user ID of this parada
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this parada.
	 *
	 * @return the user uuid of this parada
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this parada.
	 *
	 * @param userUuid the user uuid of this parada
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this parada.
	 *
	 * @return the user name of this parada
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this parada.
	 *
	 * @param userName the user name of this parada
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this parada.
	 *
	 * @return the create date of this parada
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this parada.
	 *
	 * @param createDate the create date of this parada
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this parada.
	 *
	 * @return the modified date of this parada
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this parada.
	 *
	 * @param modifiedDate the modified date of this parada
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the nombre parada of this parada.
	 *
	 * @return the nombre parada of this parada
	 */
	@AutoEscape
	public String getNombreParada();

	/**
	 * Sets the nombre parada of this parada.
	 *
	 * @param nombreParada the nombre parada of this parada
	 */
	public void setNombreParada(String nombreParada);

	/**
	 * Returns the descripcion of this parada.
	 *
	 * @return the descripcion of this parada
	 */
	@AutoEscape
	public String getDescripcion();

	/**
	 * Sets the descripcion of this parada.
	 *
	 * @param descripcion the descripcion of this parada
	 */
	public void setDescripcion(String descripcion);

	/**
	 * Returns the horario of this parada.
	 *
	 * @return the horario of this parada
	 */
	@AutoEscape
	public String getHorario();

	/**
	 * Sets the horario of this parada.
	 *
	 * @param horario the horario of this parada
	 */
	public void setHorario(String horario);

	/**
	 * Returns the ruta ID of this parada.
	 *
	 * @return the ruta ID of this parada
	 */
	public long getRutaId();

	/**
	 * Sets the ruta ID of this parada.
	 *
	 * @param rutaId the ruta ID of this parada
	 */
	public void setRutaId(long rutaId);

	/**
	 * Returns the nombre carpeta of this parada.
	 *
	 * @return the nombre carpeta of this parada
	 */
	@AutoEscape
	public String getNombreCarpeta();

	/**
	 * Sets the nombre carpeta of this parada.
	 *
	 * @param nombreCarpeta the nombre carpeta of this parada
	 */
	public void setNombreCarpeta(String nombreCarpeta);

	/**
	 * Returns the nombre archivo of this parada.
	 *
	 * @return the nombre archivo of this parada
	 */
	@AutoEscape
	public String getNombreArchivo();

	/**
	 * Sets the nombre archivo of this parada.
	 *
	 * @param nombreArchivo the nombre archivo of this parada
	 */
	public void setNombreArchivo(String nombreArchivo);

}