/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package mx.com.cuervo.rutas.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedAuditedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the Ruta service. Represents a row in the &quot;C_Ruta&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>mx.com.cuervo.rutas.model.impl.RutaModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>mx.com.cuervo.rutas.model.impl.RutaImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Ruta
 * @generated
 */
@ProviderType
public interface RutaModel
	extends BaseModel<Ruta>, GroupedModel, ShardedModel, StagedAuditedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a ruta model instance should use the {@link Ruta} interface instead.
	 */

	/**
	 * Returns the primary key of this ruta.
	 *
	 * @return the primary key of this ruta
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this ruta.
	 *
	 * @param primaryKey the primary key of this ruta
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this ruta.
	 *
	 * @return the uuid of this ruta
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this ruta.
	 *
	 * @param uuid the uuid of this ruta
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the ruta ID of this ruta.
	 *
	 * @return the ruta ID of this ruta
	 */
	public long getRutaId();

	/**
	 * Sets the ruta ID of this ruta.
	 *
	 * @param rutaId the ruta ID of this ruta
	 */
	public void setRutaId(long rutaId);

	/**
	 * Returns the group ID of this ruta.
	 *
	 * @return the group ID of this ruta
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this ruta.
	 *
	 * @param groupId the group ID of this ruta
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this ruta.
	 *
	 * @return the company ID of this ruta
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this ruta.
	 *
	 * @param companyId the company ID of this ruta
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this ruta.
	 *
	 * @return the user ID of this ruta
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this ruta.
	 *
	 * @param userId the user ID of this ruta
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this ruta.
	 *
	 * @return the user uuid of this ruta
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this ruta.
	 *
	 * @param userUuid the user uuid of this ruta
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this ruta.
	 *
	 * @return the user name of this ruta
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this ruta.
	 *
	 * @param userName the user name of this ruta
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this ruta.
	 *
	 * @return the create date of this ruta
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this ruta.
	 *
	 * @param createDate the create date of this ruta
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this ruta.
	 *
	 * @return the modified date of this ruta
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this ruta.
	 *
	 * @param modifiedDate the modified date of this ruta
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the nombre ruta of this ruta.
	 *
	 * @return the nombre ruta of this ruta
	 */
	@AutoEscape
	public String getNombreRuta();

	/**
	 * Sets the nombre ruta of this ruta.
	 *
	 * @param nombreRuta the nombre ruta of this ruta
	 */
	public void setNombreRuta(String nombreRuta);

	/**
	 * Returns the capacidad of this ruta.
	 *
	 * @return the capacidad of this ruta
	 */
	public long getCapacidad();

	/**
	 * Sets the capacidad of this ruta.
	 *
	 * @param capacidad the capacidad of this ruta
	 */
	public void setCapacidad(long capacidad);

	/**
	 * Returns the disponibilidad of this ruta.
	 *
	 * @return the disponibilidad of this ruta
	 */
	public long getDisponibilidad();

	/**
	 * Sets the disponibilidad of this ruta.
	 *
	 * @param disponibilidad the disponibilidad of this ruta
	 */
	public void setDisponibilidad(long disponibilidad);

}