/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package mx.com.cuervo.rutas.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.exportimport.kernel.lar.StagedModelType;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.kernel.util.ProxyUtil;

import java.io.Serializable;

import java.lang.reflect.Constructor;
import java.lang.reflect.InvocationHandler;

import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.function.BiConsumer;
import java.util.function.Function;

import mx.com.cuervo.rutas.model.Ruta;
import mx.com.cuervo.rutas.model.RutaModel;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model implementation for the Ruta service. Represents a row in the &quot;C_Ruta&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface </code>RutaModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link RutaImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see RutaImpl
 * @generated
 */
@ProviderType
public class RutaModelImpl extends BaseModelImpl<Ruta> implements RutaModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a ruta model instance should use the <code>Ruta</code> interface instead.
	 */
	public static final String TABLE_NAME = "C_Ruta";

	public static final Object[][] TABLE_COLUMNS = {
		{"uuid_", Types.VARCHAR}, {"rutaId", Types.BIGINT},
		{"groupId", Types.BIGINT}, {"companyId", Types.BIGINT},
		{"userId", Types.BIGINT}, {"userName", Types.VARCHAR},
		{"createDate", Types.TIMESTAMP}, {"modifiedDate", Types.TIMESTAMP},
		{"nombreRuta", Types.VARCHAR}, {"capacidad", Types.BIGINT},
		{"disponibilidad", Types.BIGINT}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("rutaId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("nombreRuta", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("capacidad", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("disponibilidad", Types.BIGINT);
	}

	public static final String TABLE_SQL_CREATE =
		"create table C_Ruta (uuid_ VARCHAR(75) null,rutaId LONG not null primary key,groupId LONG,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,nombreRuta VARCHAR(75) null,capacidad LONG,disponibilidad LONG)";

	public static final String TABLE_SQL_DROP = "drop table C_Ruta";

	public static final String ORDER_BY_JPQL = " ORDER BY ruta.rutaId ASC";

	public static final String ORDER_BY_SQL = " ORDER BY C_Ruta.rutaId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	public static final long COMPANYID_COLUMN_BITMASK = 1L;

	public static final long GROUPID_COLUMN_BITMASK = 2L;

	public static final long UUID_COLUMN_BITMASK = 4L;

	public static final long RUTAID_COLUMN_BITMASK = 8L;

	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
		_entityCacheEnabled = entityCacheEnabled;
	}

	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
		_finderCacheEnabled = finderCacheEnabled;
	}

	public RutaModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _rutaId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setRutaId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _rutaId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return Ruta.class;
	}

	@Override
	public String getModelClassName() {
		return Ruta.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<Ruta, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<Ruta, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Ruta, Object> attributeGetterFunction = entry.getValue();

			attributes.put(
				attributeName, attributeGetterFunction.apply((Ruta)this));
		}

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<Ruta, Object>> attributeSetterBiConsumers =
			getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<Ruta, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept((Ruta)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<Ruta, Object>> getAttributeGetterFunctions() {
		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<Ruta, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static Function<InvocationHandler, Ruta>
		_getProxyProviderFunction() {

		Class<?> proxyClass = ProxyUtil.getProxyClass(
			Ruta.class.getClassLoader(), Ruta.class, ModelWrapper.class);

		try {
			Constructor<Ruta> constructor =
				(Constructor<Ruta>)proxyClass.getConstructor(
					InvocationHandler.class);

			return invocationHandler -> {
				try {
					return constructor.newInstance(invocationHandler);
				}
				catch (ReflectiveOperationException roe) {
					throw new InternalError(roe);
				}
			};
		}
		catch (NoSuchMethodException nsme) {
			throw new InternalError(nsme);
		}
	}

	private static final Map<String, Function<Ruta, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<Ruta, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<Ruta, Object>> attributeGetterFunctions =
			new LinkedHashMap<String, Function<Ruta, Object>>();
		Map<String, BiConsumer<Ruta, ?>> attributeSetterBiConsumers =
			new LinkedHashMap<String, BiConsumer<Ruta, ?>>();

		attributeGetterFunctions.put("uuid", Ruta::getUuid);
		attributeSetterBiConsumers.put(
			"uuid", (BiConsumer<Ruta, String>)Ruta::setUuid);
		attributeGetterFunctions.put("rutaId", Ruta::getRutaId);
		attributeSetterBiConsumers.put(
			"rutaId", (BiConsumer<Ruta, Long>)Ruta::setRutaId);
		attributeGetterFunctions.put("groupId", Ruta::getGroupId);
		attributeSetterBiConsumers.put(
			"groupId", (BiConsumer<Ruta, Long>)Ruta::setGroupId);
		attributeGetterFunctions.put("companyId", Ruta::getCompanyId);
		attributeSetterBiConsumers.put(
			"companyId", (BiConsumer<Ruta, Long>)Ruta::setCompanyId);
		attributeGetterFunctions.put("userId", Ruta::getUserId);
		attributeSetterBiConsumers.put(
			"userId", (BiConsumer<Ruta, Long>)Ruta::setUserId);
		attributeGetterFunctions.put("userName", Ruta::getUserName);
		attributeSetterBiConsumers.put(
			"userName", (BiConsumer<Ruta, String>)Ruta::setUserName);
		attributeGetterFunctions.put("createDate", Ruta::getCreateDate);
		attributeSetterBiConsumers.put(
			"createDate", (BiConsumer<Ruta, Date>)Ruta::setCreateDate);
		attributeGetterFunctions.put("modifiedDate", Ruta::getModifiedDate);
		attributeSetterBiConsumers.put(
			"modifiedDate", (BiConsumer<Ruta, Date>)Ruta::setModifiedDate);
		attributeGetterFunctions.put("nombreRuta", Ruta::getNombreRuta);
		attributeSetterBiConsumers.put(
			"nombreRuta", (BiConsumer<Ruta, String>)Ruta::setNombreRuta);
		attributeGetterFunctions.put("capacidad", Ruta::getCapacidad);
		attributeSetterBiConsumers.put(
			"capacidad", (BiConsumer<Ruta, Long>)Ruta::setCapacidad);
		attributeGetterFunctions.put("disponibilidad", Ruta::getDisponibilidad);
		attributeSetterBiConsumers.put(
			"disponibilidad", (BiConsumer<Ruta, Long>)Ruta::setDisponibilidad);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@Override
	public String getUuid() {
		if (_uuid == null) {
			return "";
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		_columnBitmask |= UUID_COLUMN_BITMASK;

		if (_originalUuid == null) {
			_originalUuid = _uuid;
		}

		_uuid = uuid;
	}

	public String getOriginalUuid() {
		return GetterUtil.getString(_originalUuid);
	}

	@Override
	public long getRutaId() {
		return _rutaId;
	}

	@Override
	public void setRutaId(long rutaId) {
		_rutaId = rutaId;
	}

	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		_columnBitmask |= GROUPID_COLUMN_BITMASK;

		if (!_setOriginalGroupId) {
			_setOriginalGroupId = true;

			_originalGroupId = _groupId;
		}

		_groupId = groupId;
	}

	public long getOriginalGroupId() {
		return _originalGroupId;
	}

	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		_columnBitmask |= COMPANYID_COLUMN_BITMASK;

		if (!_setOriginalCompanyId) {
			_setOriginalCompanyId = true;

			_originalCompanyId = _companyId;
		}

		_companyId = companyId;
	}

	public long getOriginalCompanyId() {
		return _originalCompanyId;
	}

	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException pe) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@Override
	public String getUserName() {
		if (_userName == null) {
			return "";
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		_userName = userName;
	}

	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		_createDate = createDate;
	}

	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		_modifiedDate = modifiedDate;
	}

	@Override
	public String getNombreRuta() {
		if (_nombreRuta == null) {
			return "";
		}
		else {
			return _nombreRuta;
		}
	}

	@Override
	public void setNombreRuta(String nombreRuta) {
		_nombreRuta = nombreRuta;
	}

	@Override
	public long getCapacidad() {
		return _capacidad;
	}

	@Override
	public void setCapacidad(long capacidad) {
		_capacidad = capacidad;
	}

	@Override
	public long getDisponibilidad() {
		return _disponibilidad;
	}

	@Override
	public void setDisponibilidad(long disponibilidad) {
		_disponibilidad = disponibilidad;
	}

	@Override
	public StagedModelType getStagedModelType() {
		return new StagedModelType(
			PortalUtil.getClassNameId(Ruta.class.getName()));
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), Ruta.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public Ruta toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, Ruta>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		RutaImpl rutaImpl = new RutaImpl();

		rutaImpl.setUuid(getUuid());
		rutaImpl.setRutaId(getRutaId());
		rutaImpl.setGroupId(getGroupId());
		rutaImpl.setCompanyId(getCompanyId());
		rutaImpl.setUserId(getUserId());
		rutaImpl.setUserName(getUserName());
		rutaImpl.setCreateDate(getCreateDate());
		rutaImpl.setModifiedDate(getModifiedDate());
		rutaImpl.setNombreRuta(getNombreRuta());
		rutaImpl.setCapacidad(getCapacidad());
		rutaImpl.setDisponibilidad(getDisponibilidad());

		rutaImpl.resetOriginalValues();

		return rutaImpl;
	}

	@Override
	public int compareTo(Ruta ruta) {
		long primaryKey = ruta.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof Ruta)) {
			return false;
		}

		Ruta ruta = (Ruta)obj;

		long primaryKey = ruta.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return _entityCacheEnabled;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return _finderCacheEnabled;
	}

	@Override
	public void resetOriginalValues() {
		RutaModelImpl rutaModelImpl = this;

		rutaModelImpl._originalUuid = rutaModelImpl._uuid;

		rutaModelImpl._originalGroupId = rutaModelImpl._groupId;

		rutaModelImpl._setOriginalGroupId = false;

		rutaModelImpl._originalCompanyId = rutaModelImpl._companyId;

		rutaModelImpl._setOriginalCompanyId = false;

		rutaModelImpl._setModifiedDate = false;

		rutaModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<Ruta> toCacheModel() {
		RutaCacheModel rutaCacheModel = new RutaCacheModel();

		rutaCacheModel.uuid = getUuid();

		String uuid = rutaCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			rutaCacheModel.uuid = null;
		}

		rutaCacheModel.rutaId = getRutaId();

		rutaCacheModel.groupId = getGroupId();

		rutaCacheModel.companyId = getCompanyId();

		rutaCacheModel.userId = getUserId();

		rutaCacheModel.userName = getUserName();

		String userName = rutaCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			rutaCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			rutaCacheModel.createDate = createDate.getTime();
		}
		else {
			rutaCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			rutaCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			rutaCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		rutaCacheModel.nombreRuta = getNombreRuta();

		String nombreRuta = rutaCacheModel.nombreRuta;

		if ((nombreRuta != null) && (nombreRuta.length() == 0)) {
			rutaCacheModel.nombreRuta = null;
		}

		rutaCacheModel.capacidad = getCapacidad();

		rutaCacheModel.disponibilidad = getDisponibilidad();

		return rutaCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<Ruta, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			4 * attributeGetterFunctions.size() + 2);

		sb.append("{");

		for (Map.Entry<String, Function<Ruta, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Ruta, Object> attributeGetterFunction = entry.getValue();

			sb.append(attributeName);
			sb.append("=");
			sb.append(attributeGetterFunction.apply((Ruta)this));
			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<Ruta, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			5 * attributeGetterFunctions.size() + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<Ruta, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Ruta, Object> attributeGetterFunction = entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(attributeGetterFunction.apply((Ruta)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, Ruta>
			_escapedModelProxyProviderFunction = _getProxyProviderFunction();

	}

	private static boolean _entityCacheEnabled;
	private static boolean _finderCacheEnabled;

	private String _uuid;
	private String _originalUuid;
	private long _rutaId;
	private long _groupId;
	private long _originalGroupId;
	private boolean _setOriginalGroupId;
	private long _companyId;
	private long _originalCompanyId;
	private boolean _setOriginalCompanyId;
	private long _userId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private String _nombreRuta;
	private long _capacidad;
	private long _disponibilidad;
	private long _columnBitmask;
	private Ruta _escapedModel;

}